spring:
  application:
    name: image-app
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
aws:
  region: eu-west-1  # fallback to eu-west-1 if not set
  s3:
    bucket: shutterbox-image-app-s3-bucket
