spring:
  application:
    name: image-app
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
aws:
  region: ${AWS_REGION:eu-west-1}  # fallback to eu-west-1 if not set
  s3:
    bucket: ${BUCKET_NAME:image-app-bucket}
